//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetpakSoapClientExample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JetpakSoapClientExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Delivery: .
        /// </summary>
        internal static string JetpakSoapClientForm_setTransportAlternativeRadioButtons__Delivery__ {
            get {
                return ResourceManager.GetString("JetpakSoapClientForm_setTransportAlternativeRadioButtons__Delivery__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Latest Delivery: .
        /// </summary>
        internal static string JetpakSoapClientForm_setTransportAlternativeRadioButtons__Latest_Delivery__ {
            get {
                return ResourceManager.GetString("JetpakSoapClientForm_setTransportAlternativeRadioButtons__Latest_Delivery__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Pickup: .
        /// </summary>
        internal static string JetpakSoapClientForm_setTransportAlternativeRadioButtons__Pickup__ {
            get {
                return ResourceManager.GetString("JetpakSoapClientForm_setTransportAlternativeRadioButtons__Pickup__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking not confirmed! .
        /// </summary>
        internal static string JPSClientForm_JPSClientForm__booking_not_confirmed__ {
            get {
                return ResourceManager.GetString("JPSClientForm_JPSClientForm__booking_not_confirmed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier.
        /// </summary>
        internal static string JPSClientForm_JPSClientForm__Courier {
            get {
                return ResourceManager.GetString("JPSClientForm_JPSClientForm__Courier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        internal static string JPSClientForm_JPSClientForm__Flight {
            get {
                return ResourceManager.GetString("JPSClientForm_JPSClientForm__Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transport alternatives found.
        /// </summary>
        internal static string JPSClientForm_JPSClientForm__No_transport_alternatives {
            get {
                return ResourceManager.GetString("JPSClientForm_JPSClientForm__No_transport_alternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport alternatives not set. .
        /// </summary>
        internal static string JPSClientForm_JPSClientForm__Transport_alternatives_not_set__ {
            get {
                return ResourceManager.GetString("JPSClientForm_JPSClientForm__Transport_alternatives_not_set__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking confirmed!.
        /// </summary>
        internal static string JPSClientForm_JPSClientForm_Booking_confirmed_ {
            get {
                return ResourceManager.GetString("JPSClientForm_JPSClientForm_Booking_confirmed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetpak booking reference: .
        /// </summary>
        internal static string JPSClientForm_JPSClientForm_Jetpak_booking_reference__ {
            get {
                return ResourceManager.GetString("JPSClientForm_JPSClientForm_Jetpak_booking_reference__", resourceCulture);
            }
        }
    }
}
